name: assignment
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo to runner
        uses: actions/checkout@v3
      - name: installing java
        uses: actions/setup-java@v2
        with:
          distribution : 'zulu'
          java-version : 11
      - name: build using maven
        run: |
          mvn clean install
          echo "clean-installed"
          mvn clean package
          echo "clean-packaged"
      - name: creating new branch
        run: |
          git config --local user.name prasad
          git config --local user.email prasadpasam6@gmail.com
          git checkout -b artefacts-store
          git push https://${{ GITHUB_TOKEN }}@github.com/${{ github.repository }}.git artefacts-store
      - uses: actions/upload-artifact@v3
        with:
          name: uploading artifacts
          path: target/*


        
      




